stages:
  - triggers

trigger-jetbrains:
  stage: triggers
  trigger:
    include: clients/JetBrains/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - clients/JetBrains/**/*

#trigger-vscode:
#  stage: triggers
#  trigger:
#    include: clients/VSCode/.gitlab-ci.yml
#    strategy: depend
#  rules:
#    - changes:
#        - clients/VSCode/**/*
#
#trigger-server:
#  stage: triggers
#  trigger:
#    include: server/.gitlab-ci.yml
#    strategy: depend
#  rules:
#    - changes:
#        - server/**/*
