workflow:
  rules:
    - when : always

stages:
  - build
  - test

default:
  interruptible: true

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/jetbrains-ci:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG clients/JetBrains/
    - docker push $IMAGE_TAG
  rules:
    - changes:
        - clients/JetBrains/Dockerfile
    - when: manual
      allow_failure: true

linting:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE/jetbrains-ci:latest
  script:
    - echo "running ktlint..."
    - cd clients/JetBrains/go-text-template
    - ./gradlew ktlintCheck --no-configuration-cache

testing:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE/jetbrains-ci:latest
  before_script:
    - npm ci
  script:
    - echo "running tests"
    - cd clients/JetBrains/go-text-template
    - ./gradlew test --build-cache --parallel --max-workers=4 --no-watch-fs --no-configuration-cache
