workflow:
  rules:
    - when : always

stages:
  - lint
  - test

default:
  interruptible: true 

linting:
  stage: lint
  image: gradle:9.0.0-jdk21-alpine
  script:
    - echo "running ktlint..."
    - cd clients/JetBrains/go-text-template
    - ./gradlew ktlintCheck

testing:
  stage: test
  image: gradle:9.0.0-jdk21-alpine
  before_script:
    - apk add --no-cache gcompat libc6-compat
  script:
    - echo "running tests"
    - cd clients/JetBrains/go-text-template
    - ./gradlew test --no-configuration-cache
