workflow:
    rules:
        - when: always

stages:
    - build
    - lint
    - test
#  - deploy

default:
    interruptible: true

build-image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE/vscode-ci:latest
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $IMAGE_TAG clients/VSCode/
        - docker push $IMAGE_TAG
    rules:
        - changes:
              - clients/VSCode/Dockerfile
        - when: manual
          allow_failure: true

linting:
    stage: lint
    image: node:24-alpine
    before_script:
        - npm ci
    script:
        - echo "Running TSESLint"
        - npm run lint:check -w clients/VSCode

formatting:
    stage: lint
    image: node:24-alpine
    before_script:
        - npm ci
    script:
        - echo "Running Prettier"
        - npm run format:check -w clients/VSCode

testing:
    stage: test
    image:
        name: $CI_REGISTRY_IMAGE/vscode-ci:latest
    before_script:
        - apt-get update
        - apt-get upgrade -y
        - apt-get install -y --no-install-recommends xvfb xauth chromium
        - npm ci
    script:
        - echo "running tests"
        - xvfb-run --server-args="-screen 0 1920x1080x24" npm test -w clients/VSCode
