//TESTS GENERATED BY LLM FROM JETBRAINS TESTS
import * as assert from "assert";
import { after, before } from "mocha";
import * as vscode from "vscode";
import { cleanupDocument, createDocument } from "./utils";

suite("Completion Test Suite", () => {
    before(async () => {
        await new Promise((resolve) => setTimeout(resolve, 2000));
    });

    after(() => {
        vscode.window.showInformationMessage("All completion tests done!");
    });

    async function getCompletions(uri: vscode.Uri, position: vscode.Position) {
        return await vscode.commands.executeCommand<vscode.CompletionList>(
            "vscode.executeCompletionItemProvider",
            uri,
            position,
        );
    }

    function getLabels(
        completions: vscode.CompletionList | undefined,
    ): string[] {
        if (!completions) return [];
        return completions.items.map((item) =>
            typeof item.label === "string" ? item.label : item.label.label,
        );
    }

    test("Dollar sign always suggested", async () => {
        const { tmplUri } = await createDocument(
            "completion-dollar.tmpl",
            "{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(0, 2),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("$"), "Expected '$' in completions");
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot always suggested", async () => {
        const { tmplUri } = await createDocument("completion-dot.tmpl", "{{}}");
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(0, 2),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("."), "Expected '.' in completions");
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Multiple variables suggested", async () => {
        const { tmplUri } = await createDocument(
            "completion-multi.tmpl",
            "{{$a := a}}\n{{$b := b}}\n{{$c := c}}\n{{$d := d}}\n{{$e := e}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(5, 2),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("$a"));
            assert.ok(labels.includes("$b"));
            assert.ok(labels.includes("$c"));
            assert.ok(labels.includes("$d"));
            assert.ok(labels.includes("$e"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variables are suggested in scope", async () => {
        const { tmplUri } = await createDocument(
            "completion-scope-in.tmpl",
            "{{range $a, $b := .}}\n{{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("$a"));
            assert.ok(labels.includes("$b"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variables are not suggested outside scope", async () => {
        const { tmplUri } = await createDocument(
            "completion-scope-out.tmpl",
            "{{range $a, $b := .}}\n{{end}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            assert.ok(!labels.includes("$a"));
            assert.ok(!labels.includes("$b"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variable suggested correctly on partial match with dollar sign", async () => {
        const { tmplUri } = await createDocument(
            "completion-partial-dollar.tmpl",
            "{{$variable := 123}}\n{{$b := b}}\n{{$va}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 5),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes("variable") || labels.includes("$variable"),
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variable suggested correctly on partial match without dollar sign", async () => {
        const { tmplUri } = await createDocument(
            "completion-partial-no-dollar.tmpl",
            "{{$variable := 123}}\n{{$b := b}}\n{{va}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 4),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("$variable"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variables are suggested in with and if scopes", async () => {
        const { tmplUri } = await createDocument(
            "completion-with-if.tmpl",
            "{{with $x := .Field}}\n    {{}}\n{{end}}\n{{if $y := .Field}}\n    {{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            // Check 'with' block
            let list = await getCompletions(tmplUri, new vscode.Position(1, 6));
            let labels = getLabels(list);
            assert.ok(labels.includes("$x"), "Expected $x inside 'with'");

            // Check 'if' block
            list = await getCompletions(tmplUri, new vscode.Position(4, 6));
            labels = getLabels(list);
            assert.ok(labels.includes("$y"), "Expected $y inside 'if'");
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variables are not suggested outside with and if scopes", async () => {
        const { tmplUri } = await createDocument(
            "completion-with-if-out.tmpl",
            "{{with $x := .Field}}{{end}}\n{{if $y := .Field}}{{end}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            assert.ok(!labels.includes("$x"));
            assert.ok(!labels.includes("$y"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Multi assignment variables", async () => {
        const { tmplUri } = await createDocument(
            "completion-multi-assign.tmpl",
            "{{$a, $b := myFunc}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            assert.ok(labels.includes("$a"));
            assert.ok(labels.includes("$b"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Variables are not suggested inside comments", async () => {
        const { tmplUri } = await createDocument(
            "completion-comments.tmpl",
            "{{$va := 1}}\n{{/* {{$v}} */}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 9),
            );
            const labels = getLabels(list);
            assert.ok(!labels.includes("$va"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Nested scope deduplication", async () => {
        const { tmplUri } = await createDocument(
            "completion-dedup.tmpl",
            "{{$a := 1}}\n{{range .}}\n    {{$a := 2}}\n    {{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(3, 6),
            );
            const labels = getLabels(list);
            const count = labels.filter((lbl) => lbl === "$a").length;
            assert.strictEqual(count, 1, "Expected $a to be deduplicated");
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Prevent completions after dot", async () => {
        const { tmplUri } = await createDocument(
            "completion-after-dot.tmpl",
            "{{$user := .}}\n{{$user.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 8),
            );
            const labels = getLabels(list);
            assert.ok(!labels.includes("$user"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Pipeline and function argument completions", async () => {
        const { tmplUri } = await createDocument(
            "completion-pipeline-args.tmpl",
            '{{$myVar := 123}}\n{{ "foo" | myFunc $ }}\n{{ myFunc 123 "test" $ }}',
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            // Check pipeline
            let list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 19),
            );
            let labels = getLabels(list);
            assert.ok(labels.includes("myVar") || labels.includes("$myVar"));

            // Check func args
            list = await getCompletions(tmplUri, new vscode.Position(2, 21));
            labels = getLabels(list);
            assert.ok(labels.includes("myVar") || labels.includes("$myVar"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Global vs Local isolation in define blocks", async () => {
        const { tmplUri } = await createDocument(
            "completion-define-iso.tmpl",
            '{{define "foo"}}\n   {{$fooVar := 1}}\n{{end}}\n\n{{define "bar"}}\n   {{}}\n{{end}}',
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(5, 5),
            );
            const labels = getLabels(list);
            assert.ok(!labels.includes("$fooVar"));
        } finally {
            await cleanupDocument(tmplUri);
        }
    });
});
