//TESTS GENERATED BY LLM FROM JETBRAINS TESTS
import * as assert from "assert";
import { after, before } from "mocha";
import * as vscode from "vscode";
import { cleanupDocument, createDocument } from "./utils";

const RESOURCE_DIR = "DotFieldTestResources";

suite("Dot Fields Suggestions Test Suite", () => {
    before(async () => {
        await new Promise((resolve) => setTimeout(resolve, 1000));
    });

    after(() => {
        vscode.window.showInformationMessage(
            "All dot fields suggestions tests done!"
        );
    });

    async function getCompletions(uri: vscode.Uri, position: vscode.Position) {
        return await vscode.commands.executeCommand<vscode.CompletionList>(
            "vscode.executeCompletionItemProvider",
            uri,
            position,
        );
    }

    function getLabels(
        completions: vscode.CompletionList | undefined,
    ): string[] {
        if (!completions) return [];
        return completions.items.map((item) =>
            typeof item.label === "string" ? item.label : item.label.label,
        );
    }

    test("All completions recommended", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-test.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes(".Address"),
                "Expected '.Address' in completions",
            );
            assert.ok(
                labels.includes(".CustomerName"),
                "Expected '.CustomerName' in completions",
            );
            assert.ok(
                labels.includes(".DisplayName"),
                "Expected '.DisplayName' in completions",
            );
            assert.ok(
                labels.includes(".Items"),
                "Expected '.Items' in completions",
            );
            assert.ok(
                labels.includes(".Paid"),
                "Expected '.Paid' in completions",
            );
            assert.ok(
                labels.includes(".TotalAmount"),
                "Expected '.TotalAmount' in completions",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Nested field completions on struct field", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-nested.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{.Address.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 11),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes("Street"),
                `Expected 'Street' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes("City"),
                `Expected 'City' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes("Country"),
                `Expected 'Country' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes("Zip"),
                `Expected 'Zip' in completions, got: ${labels}`,
            );
            // Should NOT contain top-level Order fields
            assert.ok(
                !labels.includes("CustomerName"),
                "Did not expect 'CustomerName' in nested Address completions",
            );
            assert.ok(
                !labels.includes("Items"),
                "Did not expect 'Items' in nested Address completions",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Nested method completions on struct field", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-nested-methods.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{.Address.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 11),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes("Line"),
                `Expected 'Line' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes("IsLocal"),
                `Expected 'IsLocal' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes("ZipCode"),
                `Expected 'ZipCode' in completions, got: ${labels}`,
            );
            // Should NOT contain Order-level methods
            assert.ok(
                !labels.includes("DisplayName"),
                "Did not expect 'DisplayName' in Address completions",
            );
            assert.ok(
                !labels.includes("ItemCount"),
                "Did not expect 'ItemCount' in Address completions",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Methods recommended on top-level dot", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-methods.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes(".DisplayName"),
                `Expected '.DisplayName' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Summary"),
                `Expected '.Summary' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".ItemCount"),
                `Expected '.ItemCount' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".IsLargeOrder"),
                `Expected '.IsLargeOrder' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Format"),
                `Expected '.Format' in completions, got: ${labels}`,
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Invalid methods excluded", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-invalid-methods.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            assert.ok(
                !labels.includes(".badReturn"),
                "Did not expect '.badReturn' in completions",
            );
            assert.ok(
                !labels.includes(".wrongSecond"),
                "Did not expect '.wrongSecond' in completions",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("No completions on primitive field", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-primitive.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{.CustomerName.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 16),
            );
            const labels = getLabels(list);
            // Primitive string type should not have struct fields
            assert.ok(
                !labels.includes("ID"),
                "Did not expect 'ID' on primitive type",
            );
            assert.ok(
                !labels.includes("CustomerName"),
                "Did not expect 'CustomerName' on primitive type",
            );
            assert.ok(
                !labels.includes("Street"),
                "Did not expect 'Street' on primitive type",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot field completions inside if block", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-if.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{if .Paid}}\n{{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes(".Address"),
                `Expected '.Address' in if block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".CustomerName"),
                `Expected '.CustomerName' in if block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Items"),
                `Expected '.Items' in if block completions, got: ${labels}`,
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot field completions inside range block (Item type)", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-range.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{range .Items}}\n{{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            // Inside range .Items, dot should be Item type
            assert.ok(
                labels.includes(".SKU"),
                `Expected '.SKU' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Name"),
                `Expected '.Name' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Qty"),
                `Expected '.Qty' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".UnitPrice"),
                `Expected '.UnitPrice' in range block completions, got: ${labels}`,
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot field completions inside range block (Item methods)", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-range-methods.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{range .Items}}\n{{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            assert.ok(
                labels.includes(".Label"),
                `Expected '.Label' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Total"),
                `Expected '.Total' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".IsExpensive"),
                `Expected '.IsExpensive' in range block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Describe"),
                `Expected '.Describe' in range block completions, got: ${labels}`,
            );
            // Should NOT contain Order-level methods
            assert.ok(
                !labels.includes(".DisplayName"),
                "Did not expect '.DisplayName' in Item range block",
            );
            assert.ok(
                !labels.includes(".ItemCount"),
                "Did not expect '.ItemCount' in Item range block",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot field completions inside with block (Address type)", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-with.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{with .Address}}\n{{}}\n{{end}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(2, 2),
            );
            const labels = getLabels(list);
            // Inside with .Address, dot should be Address type
            assert.ok(
                labels.includes(".Street"),
                `Expected '.Street' in with block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".City"),
                `Expected '.City' in with block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Country"),
                `Expected '.Country' in with block completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Zip"),
                `Expected '.Zip' in with block completions, got: ${labels}`,
            );
            // Should NOT contain Order-level fields
            assert.ok(
                !labels.includes(".CustomerName"),
                "Did not expect '.CustomerName' in Address with block",
            );
            assert.ok(
                !labels.includes(".Items"),
                "Did not expect '.Items' in Address with block",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("No builtins in dot completions", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-no-builtins.tmpl`,
            "{{/*gotype: cg/model.Order*/}}\n{{.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 3),
            );
            const labels = getLabels(list);
            assert.ok(
                !labels.includes("len"),
                "Did not expect 'len' in dot completions",
            );
            assert.ok(
                !labels.includes("eq"),
                "Did not expect 'eq' in dot completions",
            );
            assert.ok(
                !labels.includes("html"),
                "Did not expect 'html' in dot completions",
            );
            assert.ok(
                !labels.includes("print"),
                "Did not expect 'print' in dot completions",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("No struct field completions without gotype", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-no-gotype.tmpl`,
            "{{.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(0, 3),
            );
            const labels = getLabels(list);
            assert.ok(
                !labels.includes("Address"),
                "Did not expect 'Address' without gotype annotation",
            );
            assert.ok(
                !labels.includes("CustomerName"),
                "Did not expect 'CustomerName' without gotype annotation",
            );
            assert.ok(
                !labels.includes("Items"),
                "Did not expect 'Items' without gotype annotation",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });

    test("Dot field completions with Address gotype", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-address-type.tmpl`,
            "{{/*gotype: cg/model.Address*/}}\n{{}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 2),
            );
            const labels = getLabels(list);
            // Should suggest Address fields directly
            assert.ok(
                labels.includes(".Street"),
                `Expected '.Street' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".City"),
                `Expected '.City' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Country"),
                `Expected '.Country' in completions, got: ${labels}`,
            );
            assert.ok(
                labels.includes(".Zip"),
                `Expected '.Zip' in completions, got: ${labels}`,
            );
            // Should NOT contain Order fields
            assert.ok(
                !labels.includes(".CustomerName"),
                "Did not expect '.CustomerName' with Address gotype",
            );
            assert.ok(
                !labels.includes(".Items"),
                "Did not expect '.Items' with Address gotype",
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });


    //This test suffers from the double dot bug, but the behaviour is important so it tests as if that was intended behaviour
    //Will have to be changed when the double dot bug is fixed
    test("Multiple chained dots on recursive type", async () => {
        const { tmplUri } = await createDocument(
            `${RESOURCE_DIR}/dot-fields-chained.tmpl`,
            "{{/*gotype: cg/model.Tree*/}}\n{{.Left.Left.Left.Left.Left.}}",
        );
        try {
            await new Promise((resolve) => setTimeout(resolve, 200));
            const list = await getCompletions(
                tmplUri,
                new vscode.Position(1, 27),
            );
            const labels = getLabels(list);
            assert.ok(
                //Double dot bug
                labels.includes(".Left"),
                `Expected 'Left' in chained completions, got: ${labels}`,
            );
            assert.ok(
                //Double dot bug
                labels.includes(".Right"),
                `Expected 'Right' in chained completions, got: ${labels}`,
            );
        } finally {
            await cleanupDocument(tmplUri);
        }
    });
});
